=== magento/ece-tools/config/scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="argumentType" abstract="true" mixed="true">
        <xs:attribute name="name" use="required"/>
        <xs:attribute name="priority" type="xs:integer"/>
        <xs:attribute name="skip" type="xs:boolean"/>
    </xs:complexType>

    <xs:element name="scenario">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="step" type="stepType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="onFail">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="action" type="actionType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="array" mixed="true">
        <xs:complexContent>
            <xs:extension base="argumentType">
                <xs:sequence>
                    <xs:element name="item" type="argumentType" minOccurs="0" maxOccurs="unbounded">
                        <xs:key name="itemName">
                            <xs:selector xpath="item"/>
                            <xs:field xpath="@name"/>
                        </xs:key>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="object">
        <xs:complexContent>
            <xs:extension base="argumentType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="stepType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="arguments" type="argumentsType" minOccurs="0">
                <xs:key name="argumentName">
                    <xs:selector xpath="argument"/>
                    <xs:field xpath="@name"/>
                </xs:key>
            </xs:element>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="phpClassName"/>
        <xs:attribute name="priority" type="xs:integer"/>
        <xs:attribute name="skip" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="actionType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="phpClassName"/>
        <xs:attribute name="priority" type="xs:integer"/>
        <xs:attribute name="skip" type="xs:boolean"/>
    </xs:complexType>

    <xs:simpleType name="phpClassName">
        <xs:annotation>
            <xs:documentation>
                A string that matches a Fully Qualified Class Name from PHP, without any leading backslash
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\\?[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)(\\[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="argumentsType">
        <xs:sequence>
            <xs:element name="argument" type="argumentType" maxOccurs="unbounded">
                <xs:key name="argumentItemName">
                    <xs:selector xpath="item"/>
                    <xs:field xpath="@name"/>
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== magento/ece-tools/scenario/post-deploy.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config/scenario.xsd">
    <step name="is-deploy-failed" type="Magento\MagentoCloud\Step\PostDeploy\DeployFailed"/>
    <step name="validate-config" type="Magento\MagentoCloud\Step\ValidateConfiguration">
        <arguments>
            <argument name="logger" xsi:type="object">Psr\Log\LoggerInterface</argument>
            <argument name="validators" xsi:type="array">
                <item name="300" xsi:type="array">
                    <item name="debug-logging" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\DebugLogging</item>
                </item>
            </argument>
        </arguments>
    </step>
    <step name="enable-cron" type="Magento\MagentoCloud\Step\PostDeploy\EnableCron"/>
    <step name="backup" type="Magento\MagentoCloud\Step\PostDeploy\Backup"/>
    <step name="clean-cache" type="Magento\MagentoCloud\Step\PostDeploy\CleanCache"/>
    <step name="warm-up" type="Magento\MagentoCloud\Step\PostDeploy\WarmUp"/>
    <step name="time-to-first-byte" type="Magento\MagentoCloud\Step\PostDeploy\TimeToFirstByte"/>
</scenario>

=== magento/ece-tools/scenario/build/generate.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../config/scenario.xsd" >
    <step name="pre-build" type="Magento\MagentoCloud\Process\Build\PreBuild"/>
    <step name="set-production-mode" type="Magento\MagentoCloud\Process\SetProductionMode"/>
    <step name="validate-configuration" type="Magento\MagentoCloud\Process\ValidateConfiguration">
        <arguments>
            <argument name="validators" xsi:type="array">
                <item name="500" xsi:type="array">
                    <item name="composer" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\ComposerFile</item>
                    <item name="stage-config" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\StageConfig</item>
                </item>
                <item name="300" xsi:type="array">
                    <item name="config-file-exists" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\ConfigFileExists</item>
                    <item name="deprecated-ini" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\UnsupportedBuildOptionsIni</item>
                    <item name="stage-config-deprecated-variables" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\StageConfigDeprecatedVariables</item>
                    <item name="modules-exists" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\ModulesExists</item>
                    <item name="appropriate-version" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\AppropriateVersion</item>
                    <item name="scd-options-ignorance" xsi:type="object">Magento\MagentoCloud\Config\Validator\Build\ScdOptionsIgnorance</item>
                    <item name="ideal-state" xsi:type="object">Magento\MagentoCloud\Config\Validator\IdealState</item>
                </item>
            </argument>
        </arguments>
    </step>
    <step name="refresh-modules" type="Magento\MagentoCloud\Process\Build\RefreshModules"/>
    <step name="apply-patches" type="Magento\MagentoCloud\Process\Build\ApplyPatches"/>
    <step name="marshall-files" type="Magento\MagentoCloud\Process\Build\MarshallFiles"/>
    <step name="copy-sample-data" type="Magento\MagentoCloud\Process\Build\CopySampleData"/>
    <step name="compile-di" type="Magento\MagentoCloud\Process\Build\CompileDi"/>
    <step name="dump-autoload" type="Magento\MagentoCloud\Process\Build\ComposerDumpAutoload"/>
    <step name="deploy-static-content" type="Magento\MagentoCloud\Process\Build\DeployStaticContent">
        <arguments>
            <argument name="processes" xsi:type="array">
                <item name="generate" xsi:type="object">Magento\MagentoCloud\Process\Build\DeployStaticContent\Generate</item>
            </argument>
        </arguments>
    </step>
</scenario>

=== magento/ece-tools/tests/functional/_data/packages/ece-tools-extend/scenario/extend-deploy.xml
<?xml version="1.0"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:ece-tools:config/scenario.xsd">
    <!-- Replace remove-deploy-failed-flag step with custom step -->
    <step name="remove-deploy-failed-flag" type="Magento\EceToolExtend\Step\Deploy\RemoveDeployFailedFlag" priority="100"/>

    <!-- Skip "clean-redis-cache" sub-step in pre-deploy step -->
    <step name="pre-deploy" type="Magento\MagentoCloud\Step\Deploy\PreDeploy" priority="200">
        <arguments>
            <argument name="logger" xsi:type="object">Psr\Log\LoggerInterface</argument>
            <argument name="steps" xsi:type="array">
                <item name="clean-redis-cache" xsi:type="object" skip="true"/>
            </argument>
        </arguments>
    </step>

    <!-- Skip step "unlock-cron-jobs" -->
    <step name="unlock-cron-jobs" skip="true"/>

    <!-- Skip critical validators -->
    <step name="validate-config" type="Magento\MagentoCloud\Step\ValidateConfiguration" priority="300">
        <arguments>
            <argument name="logger" xsi:type="object">Psr\Log\LoggerInterface</argument>
            <argument name="validators" xsi:type="array">
                <item name="500" xsi:type="array">
                    <item name="database-configuration" xsi:type="object" skip="true"/>
                    <item name="search-configuration" xsi:type="object" skip="true"/>
                    <item name="resource-configuration" xsi:type="object" skip="true"/>
                    <item name="session-configuration" xsi:type="object" skip="true"/>
                    <item name="elasticsuite-integrity" xsi:type="object" skip="true"/>
                </item>
            </argument>
        </arguments>
    </step>

    <!-- Add new step into the beginning of deploy scenario -->
    <step name="new-pre-deploy-step" type="Magento\EceToolExtend\Step\Deploy\PreDeploy" priority="10"/>
</scenario>

=== magento/ece-tools/scenario/deploy.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config/scenario.xsd">
    <step name="remove-deploy-failed-flag" type="Magento\MagentoCloud\Process\Deploy\RemoveDeployFailedFlag"/>
    <step name="pre-deploy" type="Magento\MagentoCloud\Process\Deploy\PreDeploy">
        <arguments>
            <argument name="processes" xsi:type="array">
                <item name="cache" xsi:type="object">Magento\MagentoCloud\Process\Deploy\PreDeploy\ConfigUpdate\Cache</item>
                <item name="clean-static-content" xsi:type="object">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanStaticContent</item>
                <item name="clean-view-preprocessed" xsi:type="object">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanViewPreprocessed</item>
                <item name="clean-redis-cache" xsi:type="object">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanRedisCache</item>
                <item name="clean-file-cache" xsi:type="object">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanFileCache</item>
                <item name="restore-writable-dirs" xsi:type="object">Magento\MagentoCloud\Process\Deploy\PreDeploy\RestoreWritableDirectories</item>
                <item name="set-production-mode" xsi:type="object">Magento\MagentoCloud\Process\SetProductionMode</item>
            </argument>
        </arguments>
    </step>
    <step name="enable-maintenance-mode" type="Magento\MagentoCloud\Process\EnableMaintenanceMode"/>
    <step name="disable-cron" type="Magento\MagentoCloud\Process\Deploy\DisableCron"/>
    <step name="validate-config" type="Magento\MagentoCloud\Process\ValidateConfiguration">
        <arguments>
            <argument name="validators" xsi:type="array">
                <item name="500" xsi:type="array">
                    <item name="database-configuration" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\DatabaseConfiguration</item>
                    <item name="search-configuration" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\SearchConfiguration</item>
                    <item name="resource-configuration" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\ResourceConfiguration</item>
                    <item name="session-configuration" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\SessionConfiguration</item>
                    <item name="elasticsuite-integrity" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\ElasticSuiteIntegrity</item>
                </item>
                <item name="300" xsi:type="array">
                    <item name="admin-data" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\AdminData</item>
                    <item name="php-version" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\PhpVersion</item>
                    <item name="solr-integrity" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\SolrIntegrity</item>
                    <item name="es-usage" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\ElasticSearchUsage</item>
                    <item name="es-version" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\ElasticSearchVersion</item>
                    <item name="appropriate-version" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\AppropriateVersion</item>
                    <item name="scd-options-ignorance" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\ScdOptionsIgnorance</item>
                    <item name="deprecated-variables" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\DeprecatedVariables</item>
                    <item name="raw-env-variable" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\RawEnvVariable</item>
                    <item name="cloud-variables" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\MagentoCloudVariables</item>
                    <item name="json-format-variable " xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\JsonFormatVariable</item>
                    <item name="service-version" xsi:type="object">Magento\MagentoCloud\Config\Validator\Deploy\ServiceVersion</item>
                </item>
            </argument>
        </arguments>
    </step>
    <step name="unlock-cron-jobs" type="Magento\MagentoCloud\Process\Deploy\UnlockCronJobs"/>
    <step name="set-crypt-key" type="Magento\MagentoCloud\Process\Deploy\SetCryptKey"/>
    <step name="install-update" type="Magento\MagentoCloud\Process\Deploy\InstallUpdate">
        <arguments>
            <argument name="installProcesses" xsi:type="array">
                <item name="setup" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\Install\Setup</item>
                <!-- Config update start -->
                <item name="prepare-config" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\PrepareConfig</item>
                <item name="cron-consumer-runner" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\CronConsumersRunner</item>
                <item name="db-connection" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\DbConnection</item>
                <item name="amqp" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Amqp</item>
                <item name="session" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Session</item>
                <item name="search-engine" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\SearchEngine</item>
                <item name="urls" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Urls</item>
                <item name="document-root" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\DocumentRoot</item>
                <item name="lock" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Lock</item>
                <!-- Config update end -->
                <item name="config-import" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\Install\ConfigImport</item>
                <item name="reset-password" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\Install\ResetPassword</item>
            </argument>
            <argument name="updateProcesses" xsi:type="array">
                <!-- Config update start -->
                <item name="prepare-config" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\PrepareConfig</item>
                <item name="cron-consumer-runner" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\CronConsumersRunner</item>
                <item name="db-connection" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\DbConnection</item>
                <item name="amqp" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Amqp</item>
                <item name="session" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Session</item>
                <item name="search-engine" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\SearchEngine</item>
                <item name="urls" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Urls</item>
                <item name="document-root" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\DocumentRoot</item>
                <item name="lock" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Lock</item>
                <!-- Config update end -->
                <item name="set-admin-url" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\Update\SetAdminUrl</item>
                <item name="setup" xsi:type="object">Magento\MagentoCloud\Process\Deploy\InstallUpdate\Update\Setup</item>
            </argument>
        </arguments>
    </step>
    <step name="deploy-static-content" type="Magento\MagentoCloud\Process\Deploy\DeployStaticContent">
        <arguments>
            <argument name="processes" xsi:type="array">
                <item name="generate" xsi:type="object">Magento\MagentoCloud\Process\Deploy\DeployStaticContent\Generate</item>
            </argument>
        </arguments>
    </step>
    <step name="compress-static-content" type="Magento\MagentoCloud\Process\Deploy\CompressStaticContent"/>
    <step name="disable-google-analytics" type="Magento\MagentoCloud\Process\Deploy\DisableGoogleAnalytics"/>
    <!-- This process runs processes if only post_deploy hook is not configured -->
    <step name="deploy-complete" type="Magento\MagentoCloud\Process\Deploy\DeployCompletion">
        <arguments>
            <argument name="processes" xsi:type="array">
                <item name="enable-cron" xsi:type="object">Magento\MagentoCloud\Process\PostDeploy\EnableCron</item>
                <item name="backup" xsi:type="object">Magento\MagentoCloud\Process\PostDeploy\Backup</item>
                <item name="clean-cache" xsi:type="object">Magento\MagentoCloud\Process\PostDeploy\CleanCache</item>
            </argument>
        </arguments>
    </step>
    <step name="disable-maintenance-mode" type="Magento\MagentoCloud\Process\DisableMaintenanceMode"/>
</scenario>

=== magento/ece-tools/scenario/build/transfer.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../config/scenario.xsd">
    <step name="compress-static-content" type="Magento\MagentoCloud\Process\Build\CompressStaticContent"/>
    <step name="clear-init-directory" type="Magento\MagentoCloud\Process\Build\ClearInitDirectory"/>
    <step name="backup-data" type="Magento\MagentoCloud\Process\Build\BackupData">
        <arguments>
            <argument name="processes" xsi:type="array">
                <item name="static-content" xsi:type="object">Magento\MagentoCloud\Process\Build\BackupData\StaticContent</item>
                <item name="writable-dirs" xsi:type="object">Magento\MagentoCloud\Process\Build\BackupData\WritableDirectories</item>
            </argument>
        </arguments>
    </step>
</scenario>
